version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.2
    ports:
      - "9200:9200"
    environment:
      discovery.type: single-node

  kibana:
    image: docker.elastic.co/kibana/kibana:8.1.2
    ports:
      - "5601:5601"
    restart: on-failure
    depends_on:
      - elasticsearch

  filebeat-system-1:
    image: docker.elastic.co/beats/filebeat:8.1.2
    volumes:
      - ./system-1/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro  # Configuration file
      - /var/lib/docker/containers:/var/lib/docker/containers:ro            # Docker logs
      - /var/run/docker.sock:/var/run/docker.sock:ro                        # Additional information about containers
    user: root  # needed to access container logs
    restart: on-failure

  s1-service-a:
    restart: on-failure
    build: system-1/service-a
    working_dir: /app
    volumes:
      - ./system-1/service-a:/app
    ports:
      - "8081:8080"
    command: mvn clean spring-boot:run
    labels:
      collect_logs_with_filebeat: "true"

  s1-service-b:
    restart: on-failure
    build: system-1/service-b
    working_dir: /app
    volumes:
      - ./system-1/service-b:/app
    ports:
      - "8082:8080"
    command: mvn clean spring-boot:run
    labels:
      collect_logs_with_filebeat: "true"

  s1-service-c:
    restart: on-failure
    build: system-1/service-c
    working_dir: /app
    volumes:
      - ./system-1/service-c:/app
    ports:
      - "8083:8080"
    command: mvn clean spring-boot:run
    labels:
      collect_logs_with_filebeat: "true"


