version: '3.8'

services:
#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:$ELASTICSEARCH_VERSION
#    ports:
#      - "9200:9200"
#    environment:
#      discovery.type: single-node
#
#  kibana:
#    image: docker.elastic.co/kibana/kibana:$ELASTICSEARCH_VERSION
#    ports:
#      - "5601:5601"
#    restart: on-failure
#    depends_on:
#      - elasticsearch

  filebeat-system-1:
    image: docker.elastic.co/beats/filebeat:$ELASTICSEARCH_VERSION
    volumes:
      - ./system-1/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro  # Configuration file
      - /var/lib/docker/containers:/var/lib/docker/containers:ro            # Docker logs
      - /var/run/docker.sock:/var/run/docker.sock:ro                        # Additional information about containers
    user: root  # needed to access container logs
    restart: on-failure
    env_file:
      - .env

  s1-service-a:
    restart: on-failure
    build: system-1/service-a
    working_dir: /app
    volumes:
      - ./system-1/service-a:/app
    ports:
      - "8081:8080"
    command: mvn clean spring-boot:run
    labels:
      collect_logs_with_filebeat_s1: "true"

  s1-service-b:
    restart: on-failure
    build: system-1/service-b
    working_dir: /app
    volumes:
      - ./system-1/service-b:/app
    ports:
      - "8082:8080"
    command: mvn clean spring-boot:run
    labels:
      collect_logs_with_filebeat_s1: "true"

  s1-service-c:
    restart: on-failure
    build: system-1/service-c
    working_dir: /app
    volumes:
      - ./system-1/service-c:/app
    ports:
      - "8083:8080"
    command: mvn clean spring-boot:run
    labels:
      collect_logs_with_filebeat_s1: "true"

  filebeat-system-2:
    image: docker.elastic.co/beats/filebeat:$ELASTICSEARCH_VERSION
    volumes:
      - ./system-2/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro  # Configuration file
      - /var/lib/docker/containers:/var/lib/docker/containers:ro            # Docker logs
      - /var/run/docker.sock:/var/run/docker.sock:ro                        # Additional information about containers
    user: root  # needed to access container logs
    restart: on-failure
    env_file:
      - .env

  s2-service-d:
    restart: on-failure
    build: system-2/service-d
    working_dir: /app
    volumes:
      - ./system-2/service-d:/app
    ports:
      - "8091:8080"
    command: mvn clean spring-boot:run
    labels:
      collect_logs_with_filebeat_s2: "true"

  s2-service-e:
    restart: on-failure
    build: system-2/service-e
    working_dir: /app
    volumes:
      - ./system-2/service-e:/app
    ports:
      - "8092:8080"
    command: mvn clean spring-boot:run
    labels:
      collect_logs_with_filebeat_s2: "true"

  s2-service-f:
    restart: on-failure
    build: system-2/service-f
    working_dir: /app
    volumes:
      - ./system-2/service-f:/app
    ports:
      - "8093:8080"
    command: mvn clean spring-boot:run
    labels:
      collect_logs_with_filebeat_s2: "true"
