filebeat.autodiscover:
  providers:
    - type: docker
      templates:
        - condition:
            contains:
              # # add labels: collect_logs_with_filebeat: "true"
              # to get logs from a service
              container.labels.collect_logs_with_filebeat_s2: "true"
          config:
            - type: container
              format: docker
              paths:
                - "/var/lib/docker/containers/${data.docker.container.id}/*.log"
              multiline.type: pattern
              multiline.pattern: '^(\d\d\d\d-\d\d-\d\d ).*$'
              multiline.negate: true
              multiline.match: after

output.elasticsearch:
  hosts: ["https://elasticsearch:9200"]
  ssl.verification_mode: none
  username: "elastic"
  password: "changeme"
  index: "system-2-filebeat-%{[agent.version]}"
setup.template.name: "system-2-filebeat"
setup.template.pattern: "system-2-filebeat-%{[agent.version]}"

logging.metrics.enabled: false
