filebeat.autodiscover:
  providers:
    - type: docker
      templates:
        - condition:
            contains:
              # # add labels: collect_logs_with_filebeat: "true"
              # to get logs from a service
              container.labels.collect_logs_with_filebeat_s2: "true"
          config:
            - type: container
              format: docker
              paths:
                - "/var/lib/docker/containers/${data.docker.container.id}/*.log"

processors:
  - decode_json_fields:
      fields: ["message"]
      process_array: false
      max_depth: 1
      target: ""
      overwrite_keys: true
      add_error_key: true

output.elasticsearch:
  hosts: ["${ELASTICSEARCH_URL}"]
  username: "${ELASTICSEARCH_USERNAME}"
  password: "${ELASTICSEARCH_PASSWORD}"
  index: "system-1-filebeat-%{[agent.version]}"
setup.template.name: "system-1-filebeat"
setup.template.pattern: "system-1-filebeat-%{[agent.version]}"
json.keys_under_root: true
json.message_key: log

logging.metrics.enabled: false
